- hosts: localhost
  connection: local
  roles:
    - archlinux
  vars_prompt:
    - name: "my_username"
      prompt: "Enter the username you wish to use"
      private: no

    - name: "git_username"
      prompt: "Enter the name you use for git (Usually your real name)"
      private: no

    - name: "git_email"
      prompt: "Enter the email address you use for git"
      private: no

    - name: "dotfiles_repo"
      prompt: "Enter the url of your dotfiles repo"
      private: no

    - name: "dotfiles_username"
      prompt: "Enter your username for whatever site hosts your dotfiles (only needed if the repo is private)"
      private: no

    - name: "dotfiles_password"
      prompt: "Enter your password for your dotfiles repo (only needed if the repo is private)"
      private: yes
