- hosts: localhost
  connection: local
  roles:
    - archlinux
  vars_prompt:
    - name: "my_username"
      prompt: "Enter the username you wish to use"
      private: no

    - name: "git_username"
      prompt: "Enter the name you use for git (Usually your real name)"
      private: no

    - name: "git_email"
      prompt: "Enter the email address you use for git"
      private: no
