---
- name: Install git
  pacman:
    name: git
    state: present
  become: yes

- name: Set git username
  git_config:
    name: user.name
    value: "{{ git_username }}"
    scope: global
  become: yes
  become_user: "{{ my_username }}"

- name: Set git email
  git_config:
    name: user.email
    value: "{{ git_email }}"
    scope: global
  become: yes
  become_user: "{{ my_username }}"
