---
- name: Check if stack is installed
  stat:
    path: /usr/bin/stack
  register: stack_bin

# Arch haskell packages are dynamically linked
# so we install statically linked versions from
# the AUR instead to avoid massive dependency lists
- name: Install stack
  command: /usr/bin/pacaur --noconfirm -S stack-bin
  args:
    creates: /usr/bin/stack
  register: stack_result
  until: stack_result|succeeded
  ignore_errors: True
  become: yes
  become_user: "{{ my_username }}"

- name: Report stack install failure
  fail:
    msg: "Failed to install stack from AUR: {{ stack_result.stderr }}"
  when: stack_result|failed

- name: Set up global stack project
  command: /usr/bin/stack setup
  args:
    creates: /home/{{ my_username }}/.stack/global-project
  become: yes
  become_user: "{{ my_username }}"

- name: Install haskell dev tools
  command: /usr/bin/stack install --ghc-options="-j -O2" {{ item }}
  args:
    creates: /home/{{ my_username }}/.local/bin/{{ item }}
  with_items:
    - hlint
    - ghc-mod
    - hasktags
    - codex
    - hdevtools
  become: yes
  become_user: "{{ my_username }}"
