---
- name: Install vim
  pacman:
    name: gvim
    state: present
  become: yes

- name: Create vim autoload directory
  file:
    path: /home/{{ my_username }}/.vim/autoload
    state: 'directory'
  become: yes
  become_user: "{{ my_username }}"

- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: /home/{{ my_username }}/.vim/autoload/plug.vim
  become: yes
  become_user: "{{ my_username }}"

- name: Download plugins
  expect:
    command: /usr/bin/bash -c "vim +PlugInstall +qall"
    creates: /home/{{ my_username }}/.vim/bundle
    responses:
      # Just hit enter, it's complaining about the colorscheme it's about
      # to install not being there.
      (?i)E185: ""
  become: yes
  become_user: "{{ my_username }}"
